Repository AtomicFox556/Cataclysm-EOD, pull requests merged in 2023-08, with the labels that each got.

#118 Теперь нпс используют боевые искусства
  src/character.cpp
Labels: [C++], [JSON], NPC / Factions, Melee

#117 Возможность выбора мутации
  src/character.h
  src/mutation.cpp
  src/options.cpp
Labels: [C++], [JSON], Mutations / Traits / Professions/ Hobbies, Mods

#121 Убираем ошибку в отладке
  src/debug_menu.cpp
Labels: [C++]

#123 Create veggy_dishes.json. Added carrot and squash cutlets
  data/json/EraOfDecay/items/comestibles/veggy_dishes.json
Labels: [JSON]

#125 Create veggy_dishes.json and add recipes.
  data/json/EraOfDecay/recipes/comestibles/veggy_dishes.json
Labels: [JSON]
