Repository AtomicFox556/Cataclysm-EOD, pull requests merged in 2023-04, with the labels that each got.

#66 Port options for item category spawn rate
  doc/JSON_INFO.md
  src/item_category.cpp
  src/item_category.h
  src/map.cpp
  src/options.cpp
Labels: [C++], [Markdown], <Documentation>, <Enhancement / Feature>

#74 List deconstruction result types in extended look
  src/descriptions.cpp
Labels: [C++], <Enhancement / Feature>

#83 Additional messages in log
  src/creature.cpp
  src/game.cpp
  src/mattack_actors.cpp
  src/monmove.cpp
  src/monster.cpp
  src/options.cpp
Labels: [C++], Info / User Interface

#84 Helicopter Pilot Training CBM
  data/json/EraOfDecay/bionics.json
  data/json/EraOfDecay/items/bionics.json
  data/json/itemgroups/Monsters_Animals_Lairs/harvest_cbm.json
  data/json/itemgroups/bionics.json
  data/json/npcs/exodii/exodii_merchant_itemlist.json
  src/handle_action.cpp
Labels: [C++], [JSON], Spawn, Bionics

#86 Update fluff items
  data/json/itemgroups/Locations_MapExtras/mall_item_groups.json
  data/json/itemgroups/Locations_MapExtras/mansion.json
  data/json/itemgroups/furniture.json
  data/json/itemgroups/stashes.json
  data/json/items/book/nonfiction.json
  data/json/items/fluff.json
  data/json/items/generic/bathroom_house.json
  data/json/items/toy.json
  data/json/mutations/mutation_appearance.json
  src/game.cpp
Labels: [C++], [JSON], Spawn, Mutations / Traits / Professions/ Hobbies, Fields / Furniture / Terrain / Traps
